### ISSUE TITLE
ROM vs RAM

### ISSUE THREAD

**Issue by 8BitMilli** [leiradel/qrc1#2]
Hi this is less of an issue and more of a question to confirm something. Am I right in assuming that qrc11_message through qrc11_b5_ecc is your scratch pad / working area? I want to implement this in a ROM file so I need to move any scratch pad to a different area so it is in RAM.

**Comment by leiradel** [comment]
Hi,

Yes, everything in the `qrc11_ram.asm` files must be located in RAM. `qrc11_rom.asm` can be in ROM.

**Comment by 8BitMilli** [comment]
Hi - I don't see the qrc11_rom.asm anywhere - is  this in a different 
location?

**Comment by leiradel** [comment]
It's right there in the same place as the RAM one: https://github.com/leiradel/qrc1/blob/master/src/qrc11_rom.asm
